I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 36, in script
    i 'ads'
Exception: Sayer 'i' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 36, in script
    i 'ads'
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "G:\Program Files (x86)\renpy-8.1.2-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'i' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
ProjectOPD 1.0
Mon Nov 13 20:14:46 2023
